# 1.Print 'Hello HCIA'.

In [1]:
print ('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
a=6
b=13
a+b

19

# 3.Define a list and replicate in three different ways.

In [9]:
my_list=[6,13,24,7,48]
print (my_list[:])
my_list.copy()


[6, 13, 24, 7, 48]


[6, 13, 24, 7, 48]

# 4.Define two lists and merge them together.

In [18]:
my_list1=[6,13,24,7,48]
my_list2=[9,63,12,77,64]
my_list3=my_list1+my_list2
print (my_list3[:])

[6, 13, 24, 7, 48, 9, 63, 12, 77, 64]


# 5. Get the last element of the list and print it.

In [11]:
my_list1=[6,13,24,7,48]
print (my_list[4:])

[48]


# 6.Define a tuple that contains only one element.

In [22]:
my_tuple1=(9)
print (my_tuple1)

6


# 7.Define a three-line long string.

In [24]:
my_tuple1=(9,13,31)
print (my_tuple1)

(9, 13, 31)


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [26]:
my_tuple1=(9,13,31)
for key in my_tuple1:
        print(key)

9
13
31


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [32]:
import numpy 
Mul=(8,6)
Mul2=numpy.prod(Mul)
print (Mul2)

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [49]:
import numpy 
a = ([[  0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[  0, 0, 0, 0, 0],
[  0, 0, 0, 0, 0],
[  0, 0, 0, 0, 0]])
print (a)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [57]:
import numpy 
a = numpy.array([[  0, 0, 0, 0],
[  0, 0, 0, 0],
[  0, 0, 0, 0],
[  0, 0, 0, 0],
[  0, 0, 0, 0],
[  0, 0, 0, 0]])
print (a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [55]:
import numpy 
a=numpy.arange(15).reshape(3,5) 
print (a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [56]:
import numpy 
a = numpy.array([ [2, 1, 3], [2, 2, 4] ])
b = numpy.array([ [1, 1], [3, 2], [2, 4] ])
total = a.dot(b)
print(total)


[[11 16]
 [16 22]]
